### ISSUE TITLE
转换出现问题

### ISSUE THREAD

**Issue by zhangbohnu** [htshinichi/caffe-onnx#1]
您好， 用了您的代码依然无法转换
3.模型存在问题,未保存成功:
 Op registered for Upsample is depracted in domain_version of 10

==> Context: Bad node spec: input: "layer85-act_Y" input: "layer86-upsample_Scale" output: "layer86-upsample_Y" name: "layer86-upsample" op_type: "Upsample" attribute { name: "mode" s: "nearest" type: STRING }

**Comment by ZQPei** [comment]
是这样的，onnx0.5之后，ir_version为10，从这个版本开始，Upsample变为了Resize。
所以你有以下两种方法：
1. 修改源码，把Upsample改为Resize
2. 把onnx换成0.4的版本

**Comment by gttiankai** [comment]
@ZQPei 能详细说下怎么修改源码吗? 是将 caffe-onnx 中的所有的Upsample 修改为 Resize? 还是说修改需要转换的 prototxt?

**Comment by gttiankai** [comment]
@zhangbohnu 最终你是怎么修改的啊?
