### ISSUE TITLE
caffe.LayerParameter has no field named norm_param

### ISSUE THREAD

**Issue by huiofficial** [htshinichi/caffe-onnx#17]
When I try to convert a caffe SSD model to ONNX model, a message was encountered:
`google.protobuf.text_format.ParseError: 817:3 : Message type "caffe.LayerParameter" has no field named "norm_param".`
Do you have any idea?

**Comment by huiofficial** [comment]
If you have custom layers in caffe which makes your caffe.proto is different than the one in the origin caffe code. The things you should do before convertion is:

First of all, compile your proto file with protoc

# for example
$ protoc /your/path/to/caffe_ssd.proto --python_out ./proto
Then specify the caffe proto file by replacing the line from proto import caffe_upsample_pb2 as caffe_pb2 with your module.

**Comment by devsharma15** [comment]
@kingzhong23 Hey, I am trying to use this repo to convert a pre-trained caffe SSD model into onnx. I am getting the same error as you mentioned here, can you please help me if you have solved it already.
