### ISSUE TITLE
全局pooling和Gemm问题

### ISSUE THREAD

**Issue by qihaitao** [htshinichi/caffe-onnx#4]
谢谢分享
我在转化模型的时候有一个gloablepooling，这里面没有支持造成gloablepooling的output_shape不对；
gemm的transB应该是1，shape_inference.infer_shapes（model)会报错

**Comment by qihaitao** [comment]
caffe2onnx.py 112行的elif layer.type == 'PReLU‘ 层级弄错了，导致这段代码永远不会执行，onnxruntime报错

**Comment by ZQPei** [comment]
感谢你的建议，我会晚点查看你的PR！
再次感谢

**Comment by ZQPei** [comment]
感谢你的工作。
另外，你可以提供一个模型用于测试吗？
比如说一个拥有AveragePool层的caffe模型。

**Comment by qihaitao** [comment]
https://github.com/SnailTyan/caffe-model-zoo/tree/master/ResNet-152这个是用全局pooling的
