### ISSUE TITLE
op_pname["ConvTranspose"]没有定义

### ISSUE THREAD

**Issue by gttiankai** [htshinichi/caffe-onnx#7]
在处理Deconvolution的过程中，生成节点参数的过程中。在op_name中并没有定义 "ConvTranspose"，同样的，在 op_type没有定义ConvTranspose的值。所以程序在运行过程中会产生错误。

```
 conv_pname = self.__addInputsTVIfromParams(Layers[i], op_pname["ConvTranspose"], op_ptype["ConvTranspose"])
```

**Comment by ZQPei** [comment]
Thank you for pointing out this problem. This problem has been solved.
Thanks again!
